---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - automated_security_updates
    - banner
    - clamav
    - freeipa_client
    - htop
    - persist_journald
